import { canonicalHash } from "./canonical.ts";

export const FEATURE_ROUTING_VECTOR_SCHEMA_VERSION = 1 as const;
export const FEATURE_ROUTING_VECTORS = [
  { name: "ordinary peers use frozen legacy policy", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", expected: "route_legacy" },
  { name: "ordinary peers stay legacy when Boss is advertised", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", brokerBossFeatureAdvertised: true, expected: "route_legacy" },
  { name: "local kind shortcut requires two local-public policies", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "local-public", relationship: "unrelated", expected: "POLICY_DENIED" },
  { name: "local remote-tree parent edge remains authorized", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "remote-tree", relationship: "direct-parent", expected: "direct-parent" },
  { name: "own identity-bound legacy intermediary preserves ancestor chain", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "remote-tree", relationship: "own_intermediary", expected: "ancestor-chain" },
  { name: "inherited legacy intermediary cannot authorize ancestor chain", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "remote-tree", relationship: "prototype_intermediary", action: "send", expected: "POLICY_DENIED" },
  { name: "inherited legacy intermediary cannot authorize ancestor control", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "remote-tree", relationship: "prototype_intermediary", action: "inspect_tree", expected: "POLICY_DENIED" },
  { name: "legacy intermediary key identity mismatch denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", actorPolicy: "remote-tree", targetPolicy: "remote-tree", relationship: "intermediary_key_identity_mismatch", expected: "POLICY_DENIED" },
  { name: "Boss peers use run-scoped policy", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", expected: "route_boss" },
  { name: "ordinary to Boss denied", actorClass: "ordinary", targetClass: "boss-bound", actorState: "active", targetState: "active", expected: "FEATURE_CLASS_DENIED" },
  { name: "Boss to ordinary denied", actorClass: "boss-bound", targetClass: "ordinary", actorState: "active", targetState: "active", expected: "FEATURE_CLASS_DENIED" },
  { name: "credential-only Boss denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "credential_only", targetState: "active", expected: "BINDING_INACTIVE" },
  { name: "unbound Boss denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "unbound", targetState: "active", expected: "BINDING_INACTIVE" },
  { name: "revoked Boss denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "revoked", targetState: "active", expected: "BINDING_INACTIVE" },
  { name: "replaced Boss denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "replaced", targetState: "active", expected: "BINDING_INACTIVE" },
  { name: "ended Boss denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "ended", targetState: "active", expected: "BINDING_INACTIVE" },
  { name: "missing Boss feature contract denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", featureAttestation: "missing", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "unknown Boss feature version denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", featureAttestation: "unknown_version", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "Boss feature semantics mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", featureAttestation: "semantics_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "Boss policy semantics mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", policyAttestation: "semantics_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "Boss capability digest mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", capabilityAttestation: "digest_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "unverified broker denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", brokerIdentityVerified: false, expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "registration run mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", registrationIdentity: "boss_run_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "registration participant mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", registrationIdentity: "participant_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "registration epoch mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", registrationIdentity: "binding_epoch_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "folded Boss fields on ordinary registration denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "boss_fields_under_ordinary_discriminator", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "unknown Boss registration metadata denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", downgradeAttempt: "unknown_registration_field", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "registration map key substitution denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "map_key_principal_id_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "ordinary policy identity substitution denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "policy_key_principal_id_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "ordinary registration and policy state mismatch denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "policy_state_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "Boss registration and policy state mismatch denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", downgradeAttempt: "policy_state_mismatch", expected: "FEATURE_ATTESTATION_DENIED" },
  { name: "unknown registration denied", actorClass: "unknown", targetClass: "ordinary", actorState: "missing", targetState: "active", expected: "UNKNOWN_REGISTRATION" },
  { name: "unknown ordinary action denied before legacy", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", action: "unknown", expected: "ACTION_NAMESPACE_DENIED" },
  { name: "Boss context on ordinary route denied", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", context: "boss", expected: "CONTEXT_NAMESPACE_DENIED" },
  { name: "legacy context on Boss route denied", actorClass: "boss-bound", targetClass: "boss-bound", actorState: "active", targetState: "active", context: "legacy", expected: "CONTEXT_NAMESPACE_DENIED" },
  { name: "unknown top-level routing metadata rejected", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "unknown_request_field", expected: "THROW_CONTRACT_VALIDATION" },
  { name: "folded Boss epoch in legacy context rejected", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", downgradeAttempt: "boss_epoch_in_legacy_context", expected: "THROW_CONTRACT_VALIDATION" },
  { name: "Boss direct use of frozen legacy boundary throws", actorClass: "boss-bound", targetClass: "ordinary", actorState: "active", targetState: "active", entryPoint: "legacy_boundary", expected: "THROW_CONTRACT_VALIDATION" },
  { name: "inactive ordinary direct use of frozen legacy boundary throws", actorClass: "ordinary", targetClass: "ordinary", actorState: "revoked", targetState: "active", entryPoint: "legacy_boundary", expected: "THROW_CONTRACT_VALIDATION" },
  { name: "unknown action direct use of frozen legacy boundary throws", actorClass: "ordinary", targetClass: "ordinary", actorState: "active", targetState: "active", action: "unknown", entryPoint: "legacy_boundary", expected: "THROW_CONTRACT_VALIDATION" },
  { name: "ordinary owner supervision implies dispatcher discovery", supervisorEdge: "ordinary_owner_to_owned_worker", policyClass: "ordinary", expected: "dispatcher_discover_allowed" },
  { name: "Manager Worker supervision implies dispatcher discovery", supervisorEdge: "manager_to_assigned_worker", policyClass: "boss-bound", expected: "dispatcher_discover_allowed" },
  { name: "Manager Scout supervision implies dispatcher discovery", supervisorEdge: "manager_to_assigned_scout", policyClass: "boss-bound", expected: "dispatcher_discover_allowed" },
  { name: "Boss Manager supervision implies dispatcher discovery", supervisorEdge: "boss_to_current_manager", policyClass: "boss-bound", expected: "dispatcher_discover_allowed" },
  { name: "Controller participant supervision implies dispatcher discovery", supervisorEdge: "controller_to_run_participant", policyClass: "boss-bound", expected: "dispatcher_discover_allowed" },
] as const;

export const FEATURE_ROUTING_SEMANTICS_HASH = canonicalHash(
  "agent-intercom-core/boss-run-v1/feature-routing-vectors",
  { version: FEATURE_ROUTING_VECTOR_SCHEMA_VERSION, vectors: FEATURE_ROUTING_VECTORS },
);
